version: "3"

services:
  eureka:
    image: docker_eureka
    ports:
    - 8761:8761
  proxy:
    image: docker_proxy
    depends_on:
      - eureka
    links:
      - "eureka"
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka"
    ports:
    - 9000:9000
  userInfo:
    image: docker_userinfo
    depends_on:
      - eureka
      - proxy
      - db
      - config-server
    ports:
    - 9150
    links:
      - db
      - proxy
      - eureka
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka"
  shop:
    image: docker_shop
    depends_on:
      - eureka
      - proxy
      - db
      - config-server
    ports:
      - 9150
    links:
      - db
      - proxy
      - eureka
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka"
  config-server:
    image: docker_config-server
    depends_on:
      - eureka
    links:
      - eureka
    ports:
    - 8888
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka"
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
    - database:/var/lib/mysql
volumes:
  database: