version: "3.7"

services:
  eureka:
    image: docker_eureka
    ports:
    - 8761:8761
  config-server:
    image: docker_config-server
    depends_on:
      - eureka
    ports:
    - 8888
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka"
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
    - database:/var/lib/mysql
  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - /home/ftpuser/ftp/files:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
  proxy:
    image: docker_proxy
    depends_on:
      - eureka
    links:
      - "eureka"
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka"
    ports:
      - 9000:9000
  userInfo:
    image: docker_userinfo
    depends_on:
      - eureka
      - proxy
      - db
      - config-server
    ports:
      - 9150
    environment:
      - "spring.application.name=userinfo"
      - "spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://37.252.191.48:8443/auth/realms/Blackout/protocol/openid-connect/certs"
      - "eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka"
    command: ["./wait-for-it.sh", "db:5432  ",  "--python", "app.py"]

volumes:
  database: