global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'eureka'
    scrape_interval: 20s
    static_configs:
    metrics_path: /actuator/prometheus
    consul_sd_configs:
      - server: 'eureka:8761'
    relabel_configs:
      - source_labels: ['__meta_consul_tags']
        action: keep
      - source_labels: ['__meta_consul_service']
        target_label: job
      - source_labels: ['__meta_consul_address', '__meta_consul_service_metadata_management_port']
        separator: ':'
        target_label: __address__
